- name: Terminate tagged instances
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Termination
      ec2_instance:
        state: absent
        region: '{{ region }}'
        filters:
          tag:Name: Test_ec2
        aws_access_key: '{{ aws_access_key }}'
        aws_secret_key: '{{ aws_secret_key }}'

